### ISSUE TITLE
Issue with support-for?

### ISSUE THREAD

**Issue by martindavies** [leemunroe/motherplate#11]
Hey! 

Is the support-for file missing in bower_components/normalize-scss/fork-versions/default ?

It's imported in the _normalize.scss file but isn't in the parent directory?

Thanks!

**Comment by leemunroe** [comment]
Hmm I'm having issues with this too.

![image](https://cloud.githubusercontent.com/assets/15963/17828221/98dab2c8-6640-11e6-89dc-24094f28edee.png)

Checking https://github.com/JohnAlbin/normalize-scss/issues/43 for a resolution

**Comment by leemunroe** [comment]
@martindavies Pushed a fix. Hopefully this fixes it https://github.com/leemunroe/motherplate/blob/cf302b7d92b0d68308b4c52d64b661b7962ec878/css/scss/main.scss#L2

**Comment by leemunroe** [comment]
@martindavies Did that fix things?
