### ISSUE TITLE
Use https for font import

### ISSUE THREAD

**Issue by dohliam** [leemunroe/motherplate#9]
The `@import` url [on this line](https://github.com/leemunroe/motherplate/blob/master/css/scss/main.scss#L8) should be changed to use https instead of http, because it currently causes a [mixed content error](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) that blocks importing the font on secure sites.

**Comment by leemunroe** [comment]
Fixed. Thanks!
